#!/bin/bash
# G3 Proxy deploy: build from local g3 repo and run.
# Run from deploy/:  ./deploy.sh
# Requires deploy.env in deploy/.

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
DEPLOY_ENV="${SCRIPT_DIR}/deploy.env"

if [ ! -f "$DEPLOY_ENV" ]; then
    echo "❌ deploy.env not found. Create deploy.env in deploy/ (see deploy.env.example or README)."
    exit 1
fi

echo "📋 Loading configuration from deploy.env..."
set -a
source "$DEPLOY_ENV"
set +a
ICAP_IP=${ICAP_IP:-192.168.23.6}
ICAP_PORT=${ICAP_PORT:-1344}

AUTH_MODE=${AUTH_MODE:-single_user}
USERS_FILE=${USERS_FILE:-config/users.yaml}

if [ "$AUTH_MODE" != "users_file" ] && [ "$AUTH_MODE" != "single_user" ]; then
    echo "❌ Invalid AUTH_MODE='$AUTH_MODE'. Use 'users_file' or 'single_user' in deploy.env."
    exit 1
fi

if [ "$AUTH_MODE" = "single_user" ]; then
    if [ -z "${PROXY_USER:-}" ] || [ -z "${PROXY_PASS:-}" ]; then
        echo "❌ AUTH_MODE=single_user requires PROXY_USER and PROXY_PASS in deploy.env."
        exit 1
    fi
else
    if [[ "$USERS_FILE" != /* ]]; then
        USERS_FILE="${SCRIPT_DIR}/${USERS_FILE}"
    fi
    if [ ! -f "$USERS_FILE" ]; then
        echo "❌ AUTH_MODE=users_file requires USERS_FILE to exist: $USERS_FILE"
        exit 1
    fi
fi

echo "🚀 G3 Proxy deploy (local repo)"
echo "================================"
echo ""

if [[ $EUID -eq 0 ]]; then
    echo "⚠️  Don't run as root. Use a regular user with sudo."
    exit 1
fi

if ! command -v docker &> /dev/null; then
    echo "❌ Docker is not installed."
    exit 1
fi

if docker compose version &> /dev/null; then
    COMPOSE_CMD="docker compose"
elif docker-compose --version &> /dev/null; then
    COMPOSE_CMD="docker-compose"
else
    echo "❌ Docker Compose is not installed."
    exit 1
fi

echo "📁 Using deploy dir: $SCRIPT_DIR"
mkdir -p "$SCRIPT_DIR/config" "$SCRIPT_DIR/certs" "$SCRIPT_DIR/logs"

# Certificates
if [ ! -f "$SCRIPT_DIR/certs/ca.crt" ] || [ ! -f "$SCRIPT_DIR/certs/ca.key" ]; then
    echo "🔐 Generating SSL certificates..."
    if [ -f "$SCRIPT_DIR/certs/generate-certs.sh" ]; then
        (cd "$SCRIPT_DIR/certs" && chmod +x generate-certs.sh && ./generate-certs.sh)
    elif [ -f "$SCRIPT_DIR/generate-certs.sh" ]; then
        (cd "$SCRIPT_DIR" && chmod +x generate-certs.sh && ./generate-certs.sh)
    else
        echo "❌ No generate-certs.sh found in deploy/certs or deploy/"
        exit 1
    fi
else
    echo "✅ SSL certificates already exist"
fi

# Authentication
echo ""
if [ "$AUTH_MODE" = "users_file" ]; then
    echo "🔑 Using users file: $USERS_FILE"
    USERS_DEST="$SCRIPT_DIR/config/users.yaml"
    users_src_abs="$(cd "$(dirname "$USERS_FILE")" && pwd -P)/$(basename "$USERS_FILE")"
    users_dest_abs="$(cd "$(dirname "$USERS_DEST")" && pwd -P)/$(basename "$USERS_DEST")"
    if [ "$users_src_abs" = "$users_dest_abs" ]; then
        echo "✅ Users file already in place"
    else
        cp "$USERS_FILE" "$USERS_DEST"
    fi
else
    echo "🔑 Generating single user from deploy.env..."
    if openssl passwd -6 "$PROXY_PASS" &>/dev/null; then
        CRYPT_PASS=$(openssl passwd -6 "$PROXY_PASS")
    else
        CRYPT_PASS=$(openssl passwd -1 "$PROXY_PASS")
    fi
    {
      echo "# G3 Proxy user list - generated by deploy.sh"
      echo "- name: \"$PROXY_USER\""
      echo "  token:"
      echo "    type: xcrypt_hash"
      printf '    value: "%s"\n' "$CRYPT_PASS"
    } > "$SCRIPT_DIR/config/users.yaml"
fi
echo ""

# ICAP
echo "   ICAP server: ${ICAP_IP}:${ICAP_PORT}"

G3PROXY_YAML="$SCRIPT_DIR/config/g3proxy.yaml"
if [ -f "$G3PROXY_YAML" ]; then
    if sed --version &>/dev/null; then
        sed -i "s|icap://192.168.23.6:1344/|icap://${ICAP_IP}:${ICAP_PORT}/|g" "$G3PROXY_YAML"
        sed -i "s|icap://host.docker.internal:1344/|icap://${ICAP_IP}:${ICAP_PORT}/|g" "$G3PROXY_YAML"
    else
        sed -i '' "s|icap://192.168.23.6:1344/|icap://${ICAP_IP}:${ICAP_PORT}/|g" "$G3PROXY_YAML"
        sed -i '' "s|icap://host.docker.internal:1344/|icap://${ICAP_IP}:${ICAP_PORT}/|g" "$G3PROXY_YAML"
    fi
    echo "✅ ICAP configuration updated"
fi
echo ""

# Build and run (context = parent of deploy = g3 repo)
echo "🏗️  Building images (from local g3 repo)..."
cd "$SCRIPT_DIR"
$COMPOSE_CMD build

echo ""
echo "🚀 Starting containers..."
$COMPOSE_CMD up -d

echo ""
sleep 5
if $COMPOSE_CMD ps | grep -q "running"; then
    echo "✅ G3 Proxy is running!"
    echo ""
    $COMPOSE_CMD ps
    echo ""
    echo "📝 Logs:  cd deploy && $COMPOSE_CMD logs -f"
    echo "🧪 Test:  curl -x http://USER:PASS@localhost:3128 https://www.google.com"
    echo "🔐 CA:    $SCRIPT_DIR/certs/ca.crt"
else
    echo "❌ Container failed to start. Check logs:"
    $COMPOSE_CMD logs
    exit 1
fi
